config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create]
  resource :session, only: [:create, :new, :destroy]
  resources :subs do
    resources :posts, only: [:create]
  end
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end

  resources :comments, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author,
    foreign_key: :author_id,
    class_name: :User,
    inverse_of: :comments

  belongs_to :post, inverse_of: :comments

  belongs_to :parent,
    foreign_key: :parent_comment_id,
    class_name: :Comment,
    optional: true

  has_many :child_comments,
    foreign_key: :parent_comment_id,
    class_name: :Comment,
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :subs, presence: { message: "needs at least one sub" }

  belongs_to :author,
    foreign_key: :author_id,
    class_name: :User

  has_many :post_subs, inverse_of: :post, dependent: :destroy
  has_many :subs, through: :post_subs, source: :sub
  has_many :comments, inverse_of: :post
end

app/models/post_sub.rb
class PostSub < ApplicationRecord
  belongs_to :post
  belongs_to :sub
end

app/models/sub.rb
class Sub < ApplicationRecord
  validates :title, :description, presence: true

  belongs_to :mod,
  foreign_key: :mod_id,
  class_name: :User

  has_many :post_subs, inverse_of: :sub, dependent: :destroy
  has_many :posts, through: :post_subs, source: :post
end

app/models/user.rb
class User < ApplicationRecord
  validates :password, length: {minimum: 6, allow_nil: true}
  validates :username, :password_digest, presence: true

  has_many :subs,
  foreign_key: :mod_id,
  class_name: :Sub

  has_many :comments,
    foreign_key: :author_id,
    class_name: :Comment,
    inverse_of: :author

  has_many :posts

  before_validation :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :logged_in?, :current_user

  def login(user)
    session[:session_token] = user.reset_session_token!
  end

  def logged_in?
    !!current_user
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def show
    @comment = Comment.find_by(id: params[:id])
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id

    if @comment.save
      redirect_to post_url(@comment.post)
    else
      flash[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def new
    @comment = Comment.new(post_id: params[:post_id])
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id

    if @post.save
      redirect_to subs_url
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.author_id == current_user.id && @post.update(post_params)
      redirect_to sub_url(@post.sub)
    else
      flash[:errors] = @post.errors.full_messages
      if flash[:errors].empty?
        flash[:errors] = ["incorrect user"]
      end
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to subs_url
  end

  def show
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username],
      params[:user][:password])
    if @user
      login(@user)
      redirect_to subs_url
    else
      flash[:errors] = ['invalid credentials']
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_login

  def new
    @sub = Sub.new
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.mod_id == current_user.id && @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.mod_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def destroy
    @sub = Sub.find(params[:id])
    if @sub.mod_id == current_user.id
      @sub.destroy
    else
      flash[:errors] = ['not a mod']
    end
    redirect_to subs_url
  end

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to subs_url
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type=\"hidden\" name=\"authenticity_token\" value=\"<%= form_authenticity_token %>\">".html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<form class="" action="<%= comments_url %>" method="post">
  <%= auth_token %>

  <label for="">Content
    <input type="text" name="comment[content]" value="">
  </label>

  <input type="hidden" name="comment[post_id]" value="<%= @comment.post_id %>">

  <input type="submit" name="" value="Add Comment">
</form>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% flash[:errors].try(:each) do |er| %>
      <%= er %>
    <% end %>
    <% if logged_in? %>
      <%= current_user.username %>
      <%= button_to 'Sign Out', session_url, method: :delete %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="">
  <h1>Edit Post</h1>

  <form class="" action="<%= post_url(@post) %>" method="post">
    <input type="hidden" name="_method" value="patch">
    <%= auth_token %>

    <label for="">Title
      <input type="text" name="post[title]" value="">
    </label>

    <label for="">URL
      <input type="text" name="post[url]" value="">
    </label>

    <label for="">Content
      <input type="text" name="post[content]" value="">
    </label>

    <span style="display: flex; flex-direction: column;">
      <h2>Subs</h2>
      <input type="hidden" name="post[sub_ids][]" value="">
      <% Sub.all.each do |sub| %>
        <div class="">
          <label for="">
            <input type="checkbox"
            name="post[sub_ids][]"
            value="<%= sub.id %>">
          </label>
          <%= sub.title %>
        </div>
      <% end %>
    </span>

    <input type="submit" name="" value="Update Post">
  </form>
</div>

app/views/posts/new.html.erb
<div class="">
  <h1>New Post</h1>

  <form class="" action="<%= posts_url %>" method="post">
    <%= auth_token %>

    <label for="">Title
      <input type="text" name="post[title]" value="">
    </label>

    <label for="">URL
      <input type="text" name="post[url]" value="">
    </label>

    <label for="">Content
      <input type="text" name="post[content]" value="">
    </label>

    <span style="display: flex; flex-direction: column;">
      <h2>Subs</h2>
      <input type="hidden" name="post[sub_ids][]" value="">
      <% Sub.all.each do |sub| %>
        <div class="">
          <label for="">
            <input type="checkbox"
            name="post[sub_ids][]"
            value="<%= sub.id %>">
          </label>
          <%= sub.title %>
        </div>
      <% end %>
    </span>

    <input type="submit" name="" value="Create New Post">
  </form>
</div>

app/views/posts/show.html.erb
<div class="">
  <h1><%= @post.title %></h1>

  <ul>
    <li><%= @post.url %></li>
    <li><p><%= @post.content %></p></li>
    <li><%= link_to 'Edit Post', edit_post_url(@post) %></li>
    <li><%= button_to 'Delete Post', post_url(@post), method: :delete %></li>
  </ul>

  <h3>Add Comment</h3>
  <%= link_to 'Add Comment', new_post_comment_url(@post) %>

  <h2>Comments</h2>
  <ul>
    <% @post.comments.each do |comment| %>
      <li><%= comment.content %></li>
    <% end %>
  </ul>
</div>

app/views/subs/edit.html.erb
<h1>Edit Sub</h1>
<form class="" action="<%= sub_url(@sub) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="PATCH">

  <label>Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>

  <label>Description
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
  </label>

  <input type="submit" name="" value="Update Sub">
</form>

app/views/subs/index.html.erb
<h1>All Subs</h1>

<div class="">
  <%= link_to "Make New Sub", new_sub_url %>
  <%= link_to "Create Post for Multiple Subs", new_post_url %>

  <ul>
    <% @subs.each do |sub| %>
      <li><%= link_to sub.title, sub_url(sub) %></li>
      <br>
    <% end %>
  </ul>
</div>

app/views/subs/new.html.erb
<h1>New Sub</h1>
<form class="" action="<%= subs_url %>" method="post">
  <%= auth_token %>
  <label>Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>

  <label>Description
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
  </label>

  <input type="submit" name="" value="Create New Sub">
</form>

app/views/subs/show.html.erb
<div class="">
  <h1><%= @sub.title %></h1>
  <h3><p><%= @sub.description %></p></h3>

  <ul>

    <li><%= link_to 'Edit Sub', edit_sub_url(@sub) %></li>
    <li><%= link_to 'All Subs', subs_url %></li>
  </ul>


  <h2>Add Post to Sub</h2>
  <form class="" action="<%= sub_posts_url(@sub) %>" method="post">
    <%= auth_token %>
    <label>Title
      <input type="text" name="post[title]" value="">
    </label>

    <label>URL
      <input type="text" name="post[url]" value="">
    </label>

    <label>Content
      <input type="text" name="post[content]" value="">
    </label>

    <input type="submit" name="" value="Create New Post">
  </form>

  <% @sub.posts.each do |post| %>
    <ul>
      <li><%= link_to post.title, post_url(post) %></li>
      <li><%= post.url %></li>
      <li><%= post.content %></li>
      <li><%= link_to 'Edit Post', edit_post_url(post) %></li>
      <li><%= button_to 'Delete Post', post_url(post), method: :delete %></li>
    </ul>

  <% end %>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form class="" action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Username
    <input type="text" name="user[username]" value="<%= @user.username %>">
  </label>

  <label>Password
    <input type="password" name="user[password]" value="<%= @user.password %>">
  </label>

  <input type="submit" name="" value="Sign Up">
</form>